// OptiScaler Client - A frontend for managing OptiScaler installations
// Copyright (C) 2026 Agustín Montaña (Agustinm28)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;

namespace OptiscalerClient.Models
{
    /// <summary>
    /// Pinned description of one dlssg_for_sm86 release (assets/configs/dlssg_sm86_manifest.json,
    /// generated by a maintainer-side pin script). The only source of trust at runtime: every file is
    /// downloaded from <see cref="Repo"/> at the exact <see cref="Commit"/> and must match the size,
    /// SHA-256 and (for DLLs) the signer thumbprint recorded here. A new mod version is a client
    /// change that updates this file.
    /// </summary>
    public sealed class DlssgSm86PackageManifest
    {
        public string ModVersion { get; set; } = string.Empty;
        public string Repo { get; set; } = string.Empty;
        public string Commit { get; set; } = string.Empty;
        public string SignerThumbprint { get; set; } = string.Empty;
        public List<DlssgSm86BuildEntry> Builds { get; set; } = new();

        public DlssgSm86BuildEntry? FindBuild(string? buildId) =>
            Builds.FirstOrDefault(b => string.Equals(b.Id, buildId, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>One runtime variant of the mod (e.g. "310.9", "310.1"). Builds share the INI keys.</summary>
    public sealed class DlssgSm86BuildEntry
    {
        public string Id { get; set; } = string.Empty;
        /// <summary>Highest MaxGeneratedFrames the bundled runtime honours (5 = 6X, 3 = 4X).</summary>
        public int MaxGeneratedFrames { get; set; } = 3;
        public List<DlssgSm86FileEntry> Files { get; set; } = new();

        [JsonIgnore]
        public IEnumerable<DlssgSm86FileEntry> Proxies => Files.Where(f => f.IsProxy);

        [JsonIgnore]
        public DlssgSm86FileEntry? Ini => Files.FirstOrDefault(f => !f.IsProxy);
    }

    public sealed class DlssgSm86FileEntry
    {
        /// <summary>File name as installed next to the game's executable.</summary>
        public string Name { get; set; } = string.Empty;
        /// <summary>Path inside the upstream repository at the pinned commit.</summary>
        public string Path { get; set; } = string.Empty;
        /// <summary>"proxy" for a loader DLL, "ini" for dlssg_sm86.ini.</summary>
        public string Role { get; set; } = string.Empty;
        public long Size { get; set; }
        public string Sha256 { get; set; } = string.Empty;
        public string GitBlobSha { get; set; } = string.Empty;

        [JsonIgnore]
        public bool IsProxy => string.Equals(Role, "proxy", StringComparison.OrdinalIgnoreCase);
    }

    [JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
    [JsonSerializable(typeof(DlssgSm86PackageManifest))]
    internal partial class DlssgSm86JsonContext : JsonSerializerContext
    {
    }

    /// <summary>Why dlssg_for_sm86 can't go into this game, checked in this order.</summary>
    public enum DlssgSm86Blocker
    {
        None,
        NoTargetDirectory,
        AntiCheat,
        NoDlssG,
        NotDx12,
        /// <summary>A copy of the mod placed by hand (any version) is already in the folder. Installing
        /// next to it would mix two builds in one process, so it has to be removed first.</summary>
        ManualInstall,
        NoFreeProxyName
    }

    /// <summary>Who already holds a proxy file name in the target folder.</summary>
    public enum DlssgSm86ProxyOwner
    {
        OptiScaler,
        Fsr4Swap,
        AsiLoader,
        ReShade,
        /// <summary>dlssg_for_sm86 itself, copied in by hand rather than installed by this app.</summary>
        ManualDlssgSm86,
        Unknown
    }

    public sealed record DlssgSm86ProxyOccupant(string FileName, DlssgSm86ProxyOwner Owner);

    public sealed class DlssgSm86Eligibility
    {
        public DlssgSm86Blocker Blocker { get; init; }
        public string? TargetDirectory { get; init; }
        /// <summary>Proxy names that would be installed (or are ours already), in install order.</summary>
        public IReadOnlyList<string> FreeProxyNames { get; init; } = Array.Empty<string>();
        public IReadOnlyList<DlssgSm86ProxyOccupant> Occupied { get; init; } = Array.Empty<DlssgSm86ProxyOccupant>();
        public bool IsEligible => Blocker == DlssgSm86Blocker.None;
    }

    /// <summary>A committed dlssg_for_sm86 install, as recorded in its backup-store manifest.</summary>
    public sealed class DlssgSm86InstallState
    {
        public string Version { get; init; } = string.Empty;
        public string Build { get; init; } = string.Empty;
        public string TargetDirectory { get; init; } = string.Empty;
        public IReadOnlyList<string> ProxyNames { get; init; } = Array.Empty<string>();
        /// <summary>MaxGeneratedFrames currently in the game's dlssg_sm86.ini, or null if unreadable.</summary>
        public int? MaxGeneratedFrames { get; init; }
    }

    public enum HagsState
    {
        Unknown,
        Off,
        On
    }

    /// <summary>What the section's action button does for the current selection.</summary>
    public enum DlssgSm86PendingAction
    {
        /// <summary>Installed, and the selection matches what is installed: nothing to do.</summary>
        None,
        Install,
        /// <summary>Installed, but the pinned mod version or the selected runtime differs: reinstall.</summary>
        Update,
        /// <summary>Installed with the same version and runtime: only MaxGeneratedFrames changes.</summary>
        ApplyMultiplier
    }

    /// <summary>The pending action for a selection, plus what the window needs to describe it.</summary>
    /// <param name="Action">What the action button does.</param>
    /// <param name="DownloadBytes">Bytes still to download for <see cref="DlssgSm86PendingAction.Install"/>, else 0.</param>
    /// <param name="UpdateAvailable">The installed mod version differs from the pinned one.</param>
    /// <param name="CanRun">The action can run now: there is one and the game isn't blocked.</param>
    public sealed record DlssgSm86ActionPlan(DlssgSm86PendingAction Action, long DownloadBytes, bool UpdateAvailable, bool CanRun);

    public sealed record DlssgSm86InstallResult(IReadOnlyList<string> ProxyNames, int MaxGeneratedFrames, bool MultiplierClamped);

    public sealed record DlssgSm86UninstallResult(IReadOnlyList<string> KeptModifiedFiles);

    /// <summary>MaxGeneratedFrames values the UI offers: 1 = 2X, 2 = 3X, 3 = 4X (factory), 5 = 6X.</summary>
    public static class DlssgSm86Multipliers
    {
        public const int Default = 3;
        public static readonly int[] All = { 1, 2, 3, 5 };

        public static string Label(int maxGeneratedFrames) => $"{maxGeneratedFrames + 1}X";

        /// <summary>The values offered for a build: those its runtime honours.</summary>
        public static IReadOnlyList<int> For(DlssgSm86BuildEntry build) =>
            All.Where(m => m <= build.MaxGeneratedFrames).ToArray();

        /// <summary>The highest offered value not above <paramref name="maxGeneratedFrames"/>, so a 6X
        /// choice becomes 4X on a build that tops out there.</summary>
        public static int Clamp(int maxGeneratedFrames, DlssgSm86BuildEntry build)
        {
            var offered = For(build);
            return offered.LastOrDefault(m => m <= maxGeneratedFrames, offered.Count > 0 ? offered[0] : 1);
        }
    }
}
